name: memos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
    branches: [ main ]  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/setup-node@v3
      with:
        node-version: "18"        
    
    - name: Build
      run: cd /home/runner && git clone https://github.com/usememos/memos.git
  
    - name: Build Frontend
      run: cd /home/runner/memos && mkdir /home/runner/frontend-build && cp -rf /home/runner/memos/web/. /home/runner/frontend-build && cd /home/runner/frontend-build && yarn && yarn build
      
    - name: Build Backend
      run: cd /home/runner/memos && mkdir /home/runner/backend-build && cp -rf /home/runner/memos/. /home/runner/backend-build && cp -rf /home/runner/frontend-build/dist/. /home/runner/backend-build/server/dist && cd /home/runner/backend-build && go build -o memos ./bin/server/main.go
      
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: memos
        path: /home/runner/backend-build/memos
